// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: api/siam.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RoleBinding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Email     string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role      []string `protobuf:"bytes,3,rep,name=role,proto3" json:"role,omitempty"`
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_siam_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_siam_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_api_siam_proto_rawDescGZIP(), []int{0}
}

func (x *RoleBinding) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *RoleBinding) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RoleBinding) GetRole() []string {
	if x != nil {
		return x.Role
	}
	return nil
}

type RcReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rc      int32  `protobuf:"varint,1,opt,name=rc,proto3" json:"rc,omitempty"`
	IsError bool   `protobuf:"varint,2,opt,name=isError,proto3" json:"isError,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RcReply) Reset() {
	*x = RcReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_siam_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RcReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RcReply) ProtoMessage() {}

func (x *RcReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_siam_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RcReply.ProtoReflect.Descriptor instead.
func (*RcReply) Descriptor() ([]byte, []int) {
	return file_api_siam_proto_rawDescGZIP(), []int{1}
}

func (x *RcReply) GetRc() int32 {
	if x != nil {
		return x.Rc
	}
	return 0
}

func (x *RcReply) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *RcReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_siam_proto protoreflect.FileDescriptor

var file_api_siam_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x69, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x55, 0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x4d, 0x0a, 0x07,
	0x52, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x72, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x38, 0x0a, 0x08, 0x42,
	0x69, 0x6e, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x08, 0x42, 0x69, 0x6e, 0x64, 0x52,
	0x6f, 0x6c, 0x65, 0x12, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x42, 0x69,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x1a, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x63, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x46, 0x58, 0x2d, 0x50, 0x58, 0x54, 0x31, 0x2f, 0x73, 0x72, 0x65,
	0x2d, 0x69, 0x61, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_siam_proto_rawDescOnce sync.Once
	file_api_siam_proto_rawDescData = file_api_siam_proto_rawDesc
)

func file_api_siam_proto_rawDescGZIP() []byte {
	file_api_siam_proto_rawDescOnce.Do(func() {
		file_api_siam_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_siam_proto_rawDescData)
	})
	return file_api_siam_proto_rawDescData
}

var file_api_siam_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_siam_proto_goTypes = []interface{}{
	(*RoleBinding)(nil), // 0: api.RoleBinding
	(*RcReply)(nil),     // 1: api.RcReply
}
var file_api_siam_proto_depIdxs = []int32{
	0, // 0: api.BindRole.BindRole:input_type -> api.RoleBinding
	1, // 1: api.BindRole.BindRole:output_type -> api.RcReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_siam_proto_init() }
func file_api_siam_proto_init() {
	if File_api_siam_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_siam_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleBinding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_siam_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RcReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_siam_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_siam_proto_goTypes,
		DependencyIndexes: file_api_siam_proto_depIdxs,
		MessageInfos:      file_api_siam_proto_msgTypes,
	}.Build()
	File_api_siam_proto = out.File
	file_api_siam_proto_rawDesc = nil
	file_api_siam_proto_goTypes = nil
	file_api_siam_proto_depIdxs = nil
}
